const sentenceData = {
  week1: [
    // 1번
    {
      id: 'sentence1',
      level: 1,
      isFinal: false,
      korean: '꾸준히 해야 한다.',
      chinese: {
        hanzi: ['要', '坚持'],
        pinyin: ['yào', 'jiānchí'],
      },
    },
    {
      id: 'sentence1',
      level: 2,
      isFinal: false,
      korean: '공부는 꾸준히 해야 한다.',
      chinese: {
        hanzi: ['学习', '要', '坚持'],
        pinyin: ['xuéxí', 'yào', 'jiānchí'],
      },
    },
    {
      id: 'sentence1',
      level: 3,
      isFinal: false,
      korean: '공부는 꾸준히 해야 하고, ...하면 안 된다.',
      chinese: {
        hanzi: ['学习', '要', '坚持', '不要'],
        pinyin: ['xuéxí', 'yào', 'jiānchí', 'bú yào'],
      },
    },
    {
      id: 'sentence1',
      level: 4,
      isFinal: true,
      korean: '공부는 꾸준히 해야 하고, 중간에 포기하면 안 된다.',
      chinese: {
        hanzi: ['学习', '要', '坚持', '不要', '半途', '而', '废'],
        pinyin: ['xuéxí', 'yào', 'jiānchí', 'bú yào', 'bàntú', 'ér', 'fèi'],
      },
    },

    // 2번
    {
      id: 'sentence2',
      level: 1,
      isFinal: false,
      korean: '많이 피곤하다.',
      chinese: {
        hanzi: ['很', '累'],
        pinyin: ['hěn', 'lèi'],
      },
    },
    {
      id: 'sentence2',
      level: 2,
      isFinal: false,
      korean: '비록 많이 피곤하지만, ......',
      chinese: {
        hanzi: ['尽管', '很', '累'],
        pinyin: ['jǐnguǎn', 'hěn', 'lèi'],
      },
    },
    {
      id: 'sentence2',
      level: 3,
      isFinal: false,
      korean: '비록 많이 피곤하지만, 그래도 끝내야 한다.',
      chinese: {
        hanzi: ['尽管', '很', '累', '也', '要', '做', '完'],
        pinyin: ['jǐnguǎn', 'hěn', 'lèi', 'yě', 'yào', 'zuò', 'wán'],
      },
    },
    {
      id: 'sentence2',
      level: 4,
      isFinal: true,
      korean: '비록 많이 피곤하지만, 그래도 일을 끝내야 한다.',
      chinese: {
        hanzi: ['尽管', '很', '累', '也', '要', '把', '工作', '做', '完'],
        pinyin: [
          'jǐnguǎn',
          'hěn',
          'lèi',
          'yě',
          'yào',
          'bǎ',
          'gōngzuò',
          'zuò',
          'wán',
        ],
      },
    },

    // 3번
    {
      id: 'sentence3',
      level: 1,
      isFinal: false,
      korean: '시간을 바꾸다.',
      chinese: {
        hanzi: ['改', '时间'],
        pinyin: ['gǎi', 'shíjiān'],
      },
    },
    {
      id: 'sentence3',
      level: 2,
      isFinal: false,
      korean: '갑자기 시간을 바꾸다.',
      chinese: {
        hanzi: ['临时', '改', '时间'],
        pinyin: ['línshí', 'gǎi', 'shíjiān'],
      },
    },
    {
      id: 'sentence3',
      level: 3,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꾸다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间'],
        pinyin: ['lǐngdǎo', 'línshí', 'gǎi', 'shíjiān'],
      },
    },
    {
      id: 'sentence3',
      level: 4,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꿔서 야근을 해야 한다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间', '得', '加班'],
        pinyin: ['lǐngdǎo', 'línshí', 'gǎi', 'shíjiān', 'děi', 'jiābān'],
      },
    },
    {
      id: 'sentence3',
      level: 5,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꿔서 또 야근을 해야 한다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间', '又', '得', '加班'],
        pinyin: ['lǐngdǎo', 'línshí', 'gǎi', 'shíjiān', 'yòu', 'děi', 'jiābān'],
      },
    },
    {
      id: 'sentence3',
      level: 6,
      isFinal: false,
      korean: '상사가 갑자기 시간을 바꿔서 우리는 또 야근을 해야 한다.',
      chinese: {
        hanzi: ['领导', '临时', '改', '时间', '我们', '又', '得', '加班'],
        pinyin: [
          'lǐngdǎo',
          'línshí',
          'gǎi',
          'shíjiān',
          'wǒmen',
          'yòu',
          'děi',
          'jiābān',
        ],
      },
    },
    {
      id: 'sentence3',
      level: 7,
      isFinal: true,
      korean:
        '상사가 갑자기 시간을 바꿔서 우리는 또 야근을 해야 해. 짜증 나지 않냐.',
      chinese: {
        hanzi: [
          '领导',
          '临时',
          '改',
          '时间',
          '我们',
          '又',
          '得',
          '加班',
          '你',
          '说',
          '烦',
          '不烦',
        ],
        pinyin: [
          'lǐngdǎo',
          'línshí',
          'gǎi',
          'shíjiān',
          'wǒmen',
          'yòu',
          'děi',
          'jiābān',
          'nǐ',
          'shuō',
          'fán',
          'bu fán',
        ],
      },
    },
    // 4번
    {
      id: 'sentence4',
      level: 1,
      isFinal: false,
      korean: '선택을 하지 못하다.',
      chinese: {
        hanzi: ['做不出', '选择'],
        pinyin: ['zuò bu chū', 'xuǎnzé'],
      },
    },
    {
      id: 'sentence4',
      level: 2,
      isFinal: false,
      korean: '지금 선택을 하지 못하고 있다.',
      chinese: {
        hanzi: ['现在', '做不出', '选择'],
        pinyin: ['xiànzài', 'zuò bu chū', 'xuǎnzé'],
      },
    },
    {
      id: 'sentence4',
      level: 3,
      isFinal: false,
      korean: '지금 선택을 하지 못한다는 것은, 바꿔 말하면……',
      chinese: {
        hanzi: ['现在', '做', '不', '出', '选择', '换', '句', '话', '说'],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 4,
      isFinal: false,
      korean: '지금 선택을 하지 못한다는 것은, 바꿔 말하면 사실상……',
      chinese: {
        hanzi: [
          '现在',
          '做',
          '不',
          '出',
          '选择',
          '换',
          '句',
          '话',
          '说',
          '其实',
          '就是',
        ],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
          'qíshí',
          'jiù shì',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 5,
      isFinal: false,
      korean:
        '지금 선택을 하지 못한다는 것은, 바꿔 말하면 사실상 포기를 선택하는 것이다.',
      chinese: {
        hanzi: [
          '现在',
          '做',
          '不',
          '出',
          '选择',
          '换',
          '句',
          '话',
          '说',
          '其实',
          '就是',
          '选择',
          '放弃',
        ],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
          'qíshí',
          'jiù shì',
          'xuǎnzé',
          'fàngqì',
        ],
      },
    },
    {
      id: 'sentence4',
      level: 6,
      isFinal: true,
      korean:
        '지금 선택을 하지 못한다는 것은, 바꿔 말하면 사실상 포기를 선택하고 있는 것이다.',
      chinese: {
        hanzi: [
          '现在',
          '做',
          '不',
          '出',
          '选择',
          '换',
          '句',
          '话',
          '说',
          '其实',
          '就',
          '是',
          '在',
          '选择',
          '放弃',
        ],
        pinyin: [
          'xiànzài',
          'zuò',
          'bu',
          'chū',
          'xuǎnzé',
          'huàn',
          'jù',
          'huà',
          'shuō',
          'qíshí',
          'jiù',
          'shì',
          'zài',
          'xuǎnzé',
          'fàngqì',
        ],
      },
    },
    // 5번
    {
      id: 'sentence5',
      level: 1,
      isFinal: false,
      korean: '가격이 비싸다.',
      chinese: {
        hanzi: ['价格', '贵'],
        pinyin: ['jiàgé', 'guì'],
      },
    },
    {
      id: 'sentence5',
      level: 2,
      isFinal: false,
      korean: '가격이 비싼 건 괜찮은데……',
      chinese: {
        hanzi: ['不怕', '价格', '贵'],
        pinyin: ['bú pà', 'jiàgé', 'guì'],
      },
    },
    {
      id: 'sentence5',
      level: 3,
      isFinal: false,
      korean: '가격이 비싼 건 괜찮은데, ……이 걱정이다.',
      chinese: {
        hanzi: ['不怕', '价格', '贵', '就', '怕'],
        pinyin: ['bú pà', 'jiàgé', 'guì', 'jiù', 'pà'],
      },
    },
    {
      id: 'sentence5',
      level: 4,
      isFinal: true,
      korean: '가격이 비싼 건 괜찮은데, 품질이 안 좋을까 봐 걱정이다.',
      chinese: {
        hanzi: ['不怕', '价格', '贵', '就', '怕', '质量', '不', '好'],
        pinyin: ['bú pà', 'jiàgé', 'guì', 'jiù', 'pà', 'zhìliàng', 'bù', 'hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 1,
      isFinal: false,
      korean: '환경(분위기)이 좋다.',
      chinese: {
        hanzi: ['环境', '好'],
        pinyin: ['huánjìng', 'hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 2,
      isFinal: false,
      korean: '이 식당은 분위기가 좋다.',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好'],
        pinyin: ['zhè', 'jiā', 'cāntīng', 'huánjìng', 'hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 3,
      isFinal: false,
      korean: '이 식당 분위기가 좋긴 한데……',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好是好'],
        pinyin: ['zhè', 'jiā', 'cāntīng', 'huánjìng', 'hǎo shì hǎo'],
      },
    },
    {
      id: 'sentence6',
      level: 4,
      isFinal: false,
      korean: '이 식당 분위기가 좋긴 한데, 근데……',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好是好', '可'],
        pinyin: ['zhè', 'jiā', 'cāntīng', 'huánjìng', 'hǎo shì hǎo', 'kě'],
      },
    },
    {
      id: 'sentence6',
      level: 5,
      isFinal: true,
      korean: '이 식당 분위기는 좋긴 한데, (근데) 맛은 평범해.',
      chinese: {
        hanzi: ['这', '家', '餐厅', '环境', '好', '是好', '可', '味道', '一般'],
        pinyin: [
          'zhè',
          'jiā',
          'cāntīng',
          'huánjìng',
          'hǎo',
          'shì hǎo',
          'kě',
          'wèidào',
          'yìbān',
        ],
      },
    },
    {
      id: 'sentence7',
      level: 1,
      isFinal: false,
      korean: '도착했다.',
      chinese: {
        hanzi: ['到', '了'],
        pinyin: ['dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 2,
      isFinal: false,
      korean: '제시간에 도착했다.',
      chinese: {
        hanzi: ['准时', '到', '了'],
        pinyin: ['zhǔnshí', 'dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 3,
      isFinal: false,
      korean: '설마 제시간에 도착했다고?',
      chinese: {
        hanzi: ['居然', '准时', '到', '了'],
        pinyin: ['jūrán', 'zhǔnshí', 'dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 4,
      isFinal: false,
      korean: '네가 설마 제시간에 도착했다고?',
      chinese: {
        hanzi: ['你', '居然', '准时', '到', '了'],
        pinyin: ['nǐ', 'jūrán', 'zhǔnshí', 'dào', 'le'],
      },
    },
    {
      id: 'sentence7',
      level: 5,
      isFinal: false,
      korean: '네가 설마 제시간에 도착했다고? 해가 서쪽에서 떴네.',
      chinese: {
        hanzi: [
          '你',
          '居然',
          '准时',
          '到',
          '了',
          '太阳',
          '从',
          '西边',
          '出来了',
        ],
        pinyin: [
          'nǐ',
          'jūrán',
          'zhǔnshí',
          'dào',
          'le',
          'tàiyáng',
          'cóng',
          'xībiān',
          'chūlái le',
        ],
      },
    },
    {
      id: 'sentence7',
      level: 6,
      isFinal: true,
      korean: '네가 설마 제시간에 도착했다고? 진짜 해가 서쪽에서 떴네.',
      chinese: {
        hanzi: [
          '你',
          '居然',
          '准时',
          '到',
          '了',
          '真是',
          '太阳',
          '从',
          '西边',
          '出来了',
        ],
        pinyin: [
          'nǐ',
          'jūrán',
          'zhǔnshí',
          'dào',
          'le',
          'zhēnshì',
          'tàiyáng',
          'cóng',
          'xībiān',
          'chūlái le',
        ],
      },
    },
    {
      id: 'sentence8',
      level: 1,
      isFinal: false,
      korean: '걱정하다.',
      chinese: {
        hanzi: ['担心'],
        pinyin: ['dānxīn'],
      },
    },
    {
      id: 'sentence8',
      level: 2,
      isFinal: false,
      korean: '걱정하지 마.',
      chinese: {
        hanzi: ['别', '担心'],
        pinyin: ['bié', 'dānxīn'],
      },
    },
    {
      id: 'sentence8',
      level: 3,
      isFinal: true,
      korean: '걱정 마, 내가 있잖아.',
      chinese: {
        hanzi: ['别', '担心', '有', '我', '呢'],
        pinyin: ['bié', 'dānxīn', 'yǒu', 'wǒ', 'ne'],
      },
    },
    {
      id: 'sentence9',
      level: 1,
      isFinal: false,
      korean: '나에게 알려줘.',
      chinese: {
        hanzi: ['告诉', '我'],
        pinyin: ['gàosu', 'wǒ'],
      },
    },
    {
      id: 'sentence9',
      level: 2,
      isFinal: false,
      korean: '나에게 알려줘(봐).',
      chinese: {
        hanzi: ['告诉', '我', '吧'],
        pinyin: ['gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 3,
      isFinal: false,
      korean: '미리 나한테 알려줘.',
      chinese: {
        hanzi: ['提前', '告诉', '我', '吧'],
        pinyin: ['tíqián', 'gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 4,
      isFinal: false,
      korean: '미리 나한테 알려줘야지.',
      chinese: {
        hanzi: ['得', '提前', '告诉', '我', '吧'],
        pinyin: ['děi', 'tíqián', 'gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 5,
      isFinal: false,
      korean: '어쨌든 미리 나한테 알려줘야지.',
      chinese: {
        hanzi: ['怎么说也', '得', '提前', '告诉', '我', '吧'],
        pinyin: ['zěnme shuō yě', 'děi', 'tíqián', 'gàosu', 'wǒ', 'ba'],
      },
    },
    {
      id: 'sentence9',
      level: 6,
      isFinal: true,
      korean: '그는 아무리 바빠도, 어쨌든 미리 나한테 알려줘야지.',
      chinese: {
        hanzi: [
          '他',
          '再',
          '忙',
          '怎么',
          '说',
          '也',
          '得',
          '提前',
          '告诉',
          '我',
          '吧',
        ],
        pinyin: [
          'tā',
          'zài',
          'máng',
          'zěnme',
          'shuō',
          'yě',
          'děi',
          'tíqián',
          'gàosu',
          'wǒ',
          'ba',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 1,
      isFinal: false,
      korean: '지금은 …할 때다.',
      chinese: {
        hanzi: ['现在', '是', '时候'],
        pinyin: ['xiànzài', 'shì', 'shíhou'],
      },
    },
    {
      id: 'sentence10',
      level: 2,
      isFinal: false,
      korean: '이제는 …할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候了'],
        pinyin: ['xiànzài', 'shì', 'shíhou le'],
      },
    },
    {
      id: 'sentence10',
      level: 3,
      isFinal: false,
      korean: '이제는 한번 얘기해야 할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候了', '得', '谈一谈'],
        pinyin: ['xiànzài', 'shì', 'shíhou le', 'děi', 'tán yi tán'],
      },
    },
    {
      id: 'sentence10',
      level: 4,
      isFinal: false,
      korean: '이제는 진지하게 한번 얘기해야 할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候', '了', '得', '认真', '谈一谈'],
        pinyin: [
          'xiànzài',
          'shì',
          'shíhou',
          'le',
          'děi',
          'rènzhēn',
          'tán yi tán',
        ],
      },
    },
    {
      id: 'sentence10',
      level: 5,
      isFinal: true,
      korean: '이제는 우리 진지하게 한번 얘기해야 할 때가 됐다.',
      chinese: {
        hanzi: ['现在', '是', '时候', '了', '我们', '得', '认真', '谈', '一谈'],
        pinyin: [
          'xiànzài',
          'shì',
          'shíhou',
          'le',
          'wǒmen',
          'děi',
          'rènzhēn',
          'tán',
          'yi tán',
        ],
      },
    },
  ],
  week2: [
    // 1번
    {
      id: 'sentence11',
      level: 1,
      isFinal: false,
      korean: '하고 있어.',
      chinese: {
        hanzi: ['干着'],
        pinyin: ['gàn zhe'],
      },
    },
    {
      id: 'sentence11',
      level: 2,
      isFinal: false,
      korean: '하고 있어보자(해보자)',
      chinese: {
        hanzi: ['干', '着', '吧'],
        pinyin: ['gàn', 'zhe', 'ba'],
      },
    },
    {
      id: 'sentence11',
      level: 3,
      isFinal: false,
      korean: '먼저 하고 있어보자(해보자)',
      chinese: {
        hanzi: ['先', '干', '着', '吧'],
        pinyin: ['xiān', 'gàn', 'zhe', 'ba'],
      },
    },
    {
      id: 'sentence11',
      level: 4,
      isFinal: true,
      korean: '먼저 해보자, 되는 데까지 하는 거지.',
      chinese: {
        hanzi: ['先', '干', '着', '吧', '干', '到', '哪儿', '算哪儿'],
        pinyin: ['xiān', 'gàn', 'zhe', 'ba', 'gàn', 'dào', 'nǎr', 'suàn nǎr'],
      },
    },

    // 2번
    {
      id: 'sentence12',
      level: 1,
      isFinal: false,
      korean: '이번 시험',
      chinese: {
        hanzi: ['这次', '考试'],
        pinyin: ['zhècì', 'kǎoshì'],
      },
    },
    {
      id: 'sentence12',
      level: 2,
      isFinal: false,
      korean: '이번 시험은 지난번보다 (모두) ……하다.',
      chinese: {
        hanzi: ['这次', '考试', '都', '比', '上次'],
        pinyin: ['zhècì', 'kǎoshì', 'dōu', 'bǐ', 'shàngcì'],
      },
    },
    {
      id: 'sentence12',
      level: 3,
      isFinal: false,
      korean: '이번 시험은 지난번보다 훨씬 어려워졌다.',
      chinese: {
        hanzi: ['这次', '考试', '都', '比', '上次', '难到哪儿', '去', '了'],
        pinyin: [
          'zhècì',
          'kǎoshì',
          'dōu',
          'bǐ',
          'shàngcì',
          'nán dào nǎr',
          'qù',
          'le',
        ],
      },
    },
    {
      id: 'sentence12',
      level: 4,
      isFinal: false,
      korean:
        '이번 시험은 지난번보다 훨씬 어려워서, 아주 많은 사람들이 모두 ……',
      chinese: {
        hanzi: [
          '这次',
          '考试',
          '都',
          '比',
          '上次',
          '难到哪儿',
          '去',
          '了',
          '好',
          '多',
          '人',
          '都',
        ],
        pinyin: [
          'zhècì',
          'kǎoshì',
          'dōu',
          'bǐ',
          'shàngcì',
          'nán dào nǎr',
          'qù',
          'le',
          'hǎo',
          'duō',
          'rén',
          'dōu',
        ],
      },
    },
    {
      id: 'sentence12',
      level: 5,
      isFinal: true,
      korean:
        '이번 시험은 지난번보다 훨씬 어려워서, 아주 많은 사람이 (다) 통과하지 못했다.',
      chinese: {
        hanzi: [
          '这次',
          '考试',
          '都',
          '比',
          '上次',
          '难',
          '到',
          '哪儿',
          '去',
          '了',
          '好',
          '多',
          '人',
          '都',
          '没',
          '及格',
        ],
        pinyin: [
          'zhècì',
          'kǎoshì',
          'dōu',
          'bǐ',
          'shàngcì',
          'nán',
          'dào',
          'nǎr',
          'qù',
          'le',
          'hǎo',
          'duō',
          'rén',
          'dōu',
          'méi',
          'jígé',
        ],
      },
    },
    // 3번
    {
      id: 'sentence13',
      level: 1,
      isFinal: false,
      korean: '솔직히 말해서',
      chinese: {
        hanzi: ['不瞒你说'],
        pinyin: ['bù mán nǐ shuō'],
      },
    },
    {
      id: 'sentence13',
      level: 2,
      isFinal: false,
      korean: '솔직히 말해서, 나는 가고 싶어.',
      chinese: {
        hanzi: ['不瞒你说', '我', '想', '去'],
        pinyin: ['bù mán nǐ shuō', 'wǒ', 'xiǎng', 'qù'],
      },
    },
    {
      id: 'sentence13',
      level: 3,
      isFinal: false,
      korean: '솔직히 말해서, 나는 가고 싶지 않아.',
      chinese: {
        hanzi: ['不瞒', '你', '说', '我', '不', '想', '去'],
        pinyin: ['bù mán', 'nǐ', 'shuō', 'wǒ', 'bù', 'xiǎng', 'qù'],
      },
    },
    {
      id: 'sentence13',
      level: 4,
      isFinal: false,
      korean: '솔직히 말해서, 나는 별로 가고 싶지 않아.',
      chinese: {
        hanzi: ['不', '瞒', '你', '说', '我', '不', '太', '想', '去'],
        pinyin: ['bù', 'mán', 'nǐ', 'shuō', 'wǒ', 'bú', 'tài', 'xiǎng', 'qù'],
      },
    },
    {
      id: 'sentence13',
      level: 5,
      isFinal: true,
      korean: '솔직히 말해서, 나는 사실 별로 가고 싶지 않아.',
      chinese: {
        hanzi: ['不', '瞒', '你', '说', '我', '其实', '不', '太', '想', '去'],
        pinyin: [
          'bù',
          'mán',
          'nǐ',
          'shuō',
          'wǒ',
          'qíshí',
          'bú',
          'tài',
          'xiǎng',
          'qù',
        ],
      },
    },
    //14번
    {
      id: 'sentence14',
      level: 1,
      isFinal: false,
      korean: '참나, 정말이지',
      chinese: {
        hanzi: ['真是', '的'],
        pinyin: ['zhēnshì', 'de'],
      },
    },
    {
      id: 'sentence14',
      level: 2,
      isFinal: false,
      korean: '참나, 또 지각이네.',
      chinese: {
        hanzi: ['真是', '的', '又', '迟到', '了'],
        pinyin: ['zhēnshì', 'de', 'yòu', 'chídào', 'le'],
      },
    },
    {
      id: 'sentence14',
      level: 3,
      isFinal: false,
      korean: '참나, 걔 또 지각했어.',
      chinese: {
        hanzi: ['真是', '的', '他', '又', '迟到', '了'],
        pinyin: ['zhēnshì', 'de', 'tā', 'yòu', 'chídào', 'le'],
      },
    },
    {
      id: 'sentence14',
      level: 4,
      isFinal: true,
      korean: '참나, 걔는 왜 또 지각이야.',
      chinese: {
        hanzi: ['真是', '的', '他', '怎么', '又', '迟到', '了'],
        pinyin: ['zhēnshì', 'de', 'tā', 'zěnme', 'yòu', 'chídào', 'le'],
      },
    },
    //14번
    {
      id: 'sentence15',
      level: 1,
      isFinal: false,
      korean: '너무 멀다.',
      chinese: {
        hanzi: ['太', '远', '了'],
        pinyin: ['tài', 'yuǎn', 'le'],
      },
    },
    {
      id: 'sentence15',
      level: 2,
      isFinal: false,
      korean: '가자니 너무 멀고, ……',
      chinese: {
        hanzi: ['去', '吧', '太', '远', '了'],
        pinyin: ['qù', 'ba', 'tài', 'yuǎn', 'le'],
      },
    },
    {
      id: 'sentence15',
      level: 3,
      isFinal: false,
      korean: '가자니 너무 멀고, 안 가자니 기회를 놓친다.',
      chinese: {
        hanzi: ['去吧', '太', '远', '了', '不', '去', '吧', '错过', '机会'],
        pinyin: [
          'qù ba',
          'tài',
          'yuǎn',
          'le',
          'bú',
          'qù',
          'ba',
          'cuòguò',
          'jīhuì',
        ],
      },
    },
    {
      id: 'sentence15',
      level: 4,
      isFinal: false,
      korean: '가자니 너무 멀고, 안 가자니 기회를 놓칠까 봐 걱정된다.',
      chinese: {
        hanzi: [
          '去吧',
          '太',
          '远',
          '了',
          '不',
          '去',
          '吧',
          '怕',
          '错过',
          '机会',
        ],
        pinyin: [
          'qù ba',
          'tài',
          'yuǎn',
          'le',
          'bú',
          'qù',
          'ba',
          'pà',
          'cuòguò',
          'jīhuì',
        ],
      },
    },
    {
      id: 'sentence15',
      level: 5,
      isFinal: true,
      korean: '가자니 너무 멀고, 안 가자니 또 기회를 놓칠까 봐 걱정된다.',
      chinese: {
        hanzi: [
          '去吧',
          '太',
          '远',
          '了',
          '不',
          '去',
          '吧',
          '又',
          '怕',
          '错过',
          '机会',
        ],
        pinyin: [
          'qù ba',
          'tài',
          'yuǎn',
          'le',
          'bú',
          'qù',
          'ba',
          'yòu',
          'pà',
          'cuòguò',
          'jīhuì',
        ],
      },
    },

    {
      id: 'sentence16',
      level: 1,
      isFinal: false,
      korean: '그의 일',
      chinese: {
        hanzi: ['他', '的', '工作'],
        pinyin: ['tā', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence16',
      level: 2,
      isFinal: false,
      korean: '이건 그의 일이다.',
      chinese: {
        hanzi: ['这', '是', '他', '的', '工作'],
        pinyin: ['zhè', 'shì', 'tā', 'de', 'gōngzuò'],
      },
    },
    {
      id: 'sentence16',
      level: 3,
      isFinal: false,
      korean: '이건 그의 일인데, 그가 책임지지 않는다.',
      chinese: {
        hanzi: ['这', '是', '他', '的', '工作', '他', '不', '负责'],
        pinyin: ['zhè', 'shì', 'tā', 'de', 'gōngzuò', 'tā', 'bú', 'fùzé'],
      },
    },
    {
      id: 'sentence16',
      level: 4,
      isFinal: true,
      korean: '이건 그의 일인데, 그가 책임 안 지면 누가 져?',
      chinese: {
        hanzi: ['这', '是', '他', '的', '工作', '他', '不', '负责', '谁负责'],
        pinyin: [
          'zhè',
          'shì',
          'tā',
          'de',
          'gōngzuò',
          'tā',
          'bú',
          'fùzé',
          'shéi fùzé',
        ],
      },
    },

    {
      id: 'sentence17',
      level: 1,
      isFinal: false,
      korean: '사과해야 한다.',
      chinese: {
        hanzi: ['该', '道歉'],
        pinyin: ['gāi', 'dàoqiàn'],
      },
    },
    {
      id: 'sentence17',
      level: 2,
      isFinal: false,
      korean: '사과해야 할 것(사람)',
      chinese: {
        hanzi: ['该', '道歉', '的'],
        pinyin: ['gāi', 'dàoqiàn', 'de'],
      },
    },
    {
      id: 'sentence17',
      level: 3,
      isFinal: false,
      korean: '사과해야 할 건 사과한다.',
      chinese: {
        hanzi: ['该', '道歉', '的', '道歉'],
        pinyin: ['gāi', 'dàoqiàn', 'de', 'dàoqiàn'],
      },
    },
    {
      id: 'sentence17',
      level: 4,
      isFinal: false,
      korean: '책임져야 한다.',
      chinese: {
        hanzi: ['该', '负责'],
        pinyin: ['gāi', 'fùzé'],
      },
    },
    {
      id: 'sentence17',
      level: 5,
      isFinal: false,
      korean: '책임져야 할 것(사람)',
      chinese: {
        hanzi: ['该', '负责', '的'],
        pinyin: ['gāi', 'fùzé', 'de'],
      },
    },
    {
      id: 'sentence17',
      level: 6,
      isFinal: false,
      korean: '책임져야 할 건 책임진다.',
      chinese: {
        hanzi: ['该', '负责', '的', '负责'],
        pinyin: ['gāi', 'fùzé', 'de', 'fùzé'],
      },
    },
    {
      id: 'sentence17',
      level: 7,
      isFinal: true,
      korean: '사과해야 할 건 사과하고, 책임져야 할 건 책임지는 거다.',
      chinese: {
        hanzi: ['该', '道歉', '的', '道歉', '该', '负责', '的', '负责'],
        pinyin: [
          'gāi',
          'dàoqiàn',
          'de',
          'dàoqiàn',
          'gāi',
          'fùzé',
          'de',
          'fùzé',
        ],
      },
    },

    {
      id: 'sentence18',
      level: 1,
      isFinal: false,
      korean: '밖은 덥다.',
      chinese: {
        hanzi: ['外面', '热'],
        pinyin: ['wàimiàn', 'rè'],
      },
    },
    {
      id: 'sentence18',
      level: 2,
      isFinal: false,
      korean: '밖은 말도 못 하게 덥다.',
      chinese: {
        hanzi: ['外面', '热', '得', '跟', '什么', '似', '的'],
        pinyin: ['wàimiàn', 'rè', 'de', 'gēn', 'shénme', 'shì', 'de'],
      },
    },
    {
      id: 'sentence18',
      level: 3,
      isFinal: false,
      korean: '밖은 말도 못 하게 더워서 못 있겠다.',
      chinese: {
        hanzi: ['外面', '热', '得', '跟', '什么', '似', '的', '待', '不', '住'],
        pinyin: [
          'wàimiàn',
          'rè',
          'de',
          'gēn',
          'shénme',
          'shì',
          'de',
          'dài',
          'bu',
          'zhù',
        ],
      },
    },
    {
      id: 'sentence18',
      level: 4,
      isFinal: true,
      korean: '밖은 말도 못 하게 더워서 도저히 못 있겠어.',
      chinese: {
        hanzi: [
          '外面',
          '热',
          '得',
          '跟',
          '什么',
          '似',
          '的',
          '根本',
          '待',
          '不',
          '住',
        ],
        pinyin: [
          'wàimiàn',
          'rè',
          'de',
          'gēn',
          'shénme',
          'shì',
          'de',
          'gēnběn',
          'dài',
          'bu',
          'zhù',
        ],
      },
    },

    // 4번
    {
      id: 'sentence19',
      level: 1,
      isFinal: false,
      korean: '밥 한 끼',
      chinese: {
        hanzi: ['一顿饭'],
        pinyin: ['yí dùn fàn'],
      },
    },
    {
      id: 'sentence19',
      level: 2,
      isFinal: false,
      korean: '밥 한 끼다.',
      chinese: {
        hanzi: ['是', '一', '顿', '饭'],
        pinyin: ['shì', 'yí', 'dùn', 'fàn'],
      },
    },
    {
      id: 'sentence19',
      level: 3,
      isFinal: false,
      korean: '그냥 밥 한 끼잖아?',
      chinese: {
        hanzi: ['不', '就', '是', '一', '顿', '饭', '吗'],
        pinyin: ['bú', 'jiù', 'shì', 'yí', 'dùn', 'fàn', 'ma'],
      },
    },
    {
      id: 'sentence19',
      level: 4,
      isFinal: false,
      korean: '그냥 밥 한 끼잖아? 내가 살게.',
      chinese: {
        hanzi: ['不', '就', '是', '一', '顿', '饭', '吗', '我', '请'],
        pinyin: ['bú', 'jiù', 'shì', 'yí', 'dùn', 'fàn', 'ma', 'wǒ', 'qǐng'],
      },
    },
    {
      id: 'sentence19',
      level: 5,
      isFinal: true,
      korean: '그냥 밥 한 끼잖아? 내가 사면 돼.',
      chinese: {
        hanzi: [
          '不',
          '就',
          '是',
          '一',
          '顿',
          '饭',
          '吗',
          '我',
          '请',
          '就',
          '行',
          '了',
        ],
        pinyin: [
          'bú',
          'jiù',
          'shì',
          'yí',
          'dùn',
          'fàn',
          'ma',
          'wǒ',
          'qǐng',
          'jiù',
          'xíng',
          'le',
        ],
      },
    },
    // 5번

    {
      id: 'sentence20',
      level: 1,
      isFinal: false,
      korean: '안 좋은 소리를 먼저 하자면, ……',
      chinese: {
        hanzi: ['丑话', '说', '在', '前头'],
        pinyin: ['chǒuhuà', 'shuō', 'zài', 'qiántou'],
      },
    },
    {
      id: 'sentence20',
      level: 2,
      isFinal: false,
      korean: '안 좋은 소리를 먼저 하자면, 못 할 일은 그냥 ……',
      chinese: {
        hanzi: ['丑话', '说', '在', '前头', '做', '不', '到', '的', '事', '就'],
        pinyin: [
          'chǒuhuà',
          'shuō',
          'zài',
          'qiántou',
          'zuò',
          'bu',
          'dào',
          'de',
          'shì',
          'jiù',
        ],
      },
    },
    {
      id: 'sentence20',
      level: 3,
      isFinal: false,
      korean: '안 좋은 소리를 먼저 하자면, 못 할 일은 그냥 …하지 마.',
      chinese: {
        hanzi: [
          '丑话',
          '说',
          '在',
          '前头',
          '做',
          '不',
          '到',
          '的',
          '事',
          '就',
          '别',
        ],
        pinyin: [
          'chǒuhuà',
          'shuō',
          'zài',
          'qiántou',
          'zuò',
          'bu',
          'dào',
          'de',
          'shì',
          'jiù',
          'bié',
        ],
      },
    },
    {
      id: 'sentence20',
      level: 4,
      isFinal: true,
      korean: '안 좋은 소리를 먼저 하자면, 못 할 일은 그냥 약속하지 마.',
      chinese: {
        hanzi: [
          '丑话',
          '说',
          '在',
          '前头',
          '做',
          '不',
          '到',
          '的',
          '事',
          '就',
          '别',
          '答应',
        ],
        pinyin: [
          'chǒuhuà',
          'shuō',
          'zài',
          'qiántou',
          'zuò',
          'bu',
          'dào',
          'de',
          'shì',
          'jiù',
          'bié',
          'dāying',
        ],
      },
    },
  ],
  week3: [
    // 1번
    {
      id: 'sentence21',
      level: 1,
      isFinal: false,
      korean: '너는 알아.',
      chinese: {
        hanzi: ['你', '知道'],
        pinyin: ['nǐ', 'zhīdao'],
      },
    },
    {
      id: 'sentence21',
      level: 2,
      isFinal: false,
      korean: '너는 다 알아.',
      chinese: {
        hanzi: ['你', '都', '知道'],
        pinyin: ['nǐ', 'dōu', 'zhīdao'],
      },
    },
    {
      id: 'sentence21',
      level: 3,
      isFinal: false,
      korean: '상황은 네가 다 알아. (= 상황을 네가 다 알고 있다)',
      chinese: {
        hanzi: ['情况', '你', '都', '知道'],
        pinyin: ['qíngkuàng', 'nǐ', 'dōu', 'zhīdao'],
      },
    },
    {
      id: 'sentence21',
      level: 4,
      isFinal: false,
      korean:
        '상황은 네가 다 알고 있으니까, 알아서 처리해. (= 상황을 네가 다 알고 있으니까, 알아서 처리해.)',
      chinese: {
        hanzi: ['情况', '你', '都', '知道', '看着', '办', '吧'],
        pinyin: ['qíngkuàng', 'nǐ', 'dōu', 'zhīdao', 'kàn zhe', 'bàn', 'ba'],
      },
    },
    {
      id: 'sentence21',
      level: 5,
      isFinal: true,
      korean:
        '상황은 네가 다 알고 있으니까, 네가 그냥 알아서 처리해. (= 상황을 네가 다 알고 있으니까,네가 그냥 알아서 처리해.)',
      chinese: {
        hanzi: ['情况', '你', '都', '知道', '你', '就', '看', '着', '办', '吧'],
        pinyin: [
          'qíngkuàng',
          'nǐ',
          'dōu',
          'zhīdao',
          'nǐ',
          'jiù',
          'kàn',
          'zhe',
          'bàn',
          'ba',
        ],
      },
    },

    // 2번
    {
      id: 'sentence22',
      level: 1,
      isFinal: false,
      korean: '그만하자, 됐다, 그냥 넘어가자',
      chinese: {
        hanzi: ['算', '了'],
        pinyin: ['suàn', 'le'],
      },
    },
    {
      id: 'sentence22',
      level: 2,
      isFinal: false,
      korean:
        '그만두려고 한다, 그냥 넘어가려고 한다. (※이땐 한국어로 “~하려고 한다”가 자연스러움)',
      chinese: {
        hanzi: ['想算', '了'],
        pinyin: ['xiǎng suàn', 'le'],
      },
    },
    {
      id: 'sentence22',
      level: 3,
      isFinal: false,
      korean: '그냥 그만두려고 한다, 그냥 넘어가려고 한다',
      chinese: {
        hanzi: ['就', '想', '算', '了'],
        pinyin: ['jiù', 'xiǎng', 'suàn', 'le'],
      },
    },
    {
      id: 'sentence22',
      level: 4,
      isFinal: false,
      korean: '해결 안 하고 그냥 넘어가려고 해.',
      chinese: {
        hanzi: ['没解决', '就', '想', '算', '了'],
        pinyin: ['méi jiějué', 'jiù', 'xiǎng', 'suàn', 'le'],
      },
    },
    {
      id: 'sentence22',
      level: 5,
      isFinal: true,
      korean: '일은 해결 안 하고 그냥 넘어가려고? 그렇게 간단하지 않아.',
      chinese: {
        hanzi: [
          '事情',
          '没',
          '解决',
          '就',
          '想',
          '算',
          '了',
          '没',
          '那么',
          '便宜',
        ],
        pinyin: [
          'shìqing',
          'méi',
          'jiějué',
          'jiù',
          'xiǎng',
          'suàn',
          'le',
          'méi',
          'nàme',
          'piányi',
        ],
      },
    },
    // 3번
    {
      id: 'sentence23',
      level: 1,
      isFinal: false,
      korean: '이게 아니야.',
      chinese: {
        hanzi: ['不是', '这个'],
        pinyin: ['bú shì', 'zhè ge'],
      },
    },
    {
      id: 'sentence23',
      level: 2,
      isFinal: false,
      korean: '얘기하던 건 이게 아니야.',
      chinese: {
        hanzi: ['讨论的', '不是', '这个'],
        pinyin: ['tǎolùn de', 'bú shì', 'zhè ge'],
      },
    },
    {
      id: 'sentence23',
      level: 3,
      isFinal: false,
      korean: '우리가 얘기하던 건 이게 아니야(아니잖아).',
      chinese: {
        hanzi: ['我们', '讨论的', '不', '是', '这', '个'],
        pinyin: ['wǒmen', 'tǎolùn de', 'bú', 'shì', 'zhè', 'ge'],
      },
    },
    {
      id: 'sentence23',
      level: 4,
      isFinal: false,
      korean: '무슨 소리야, 우리가 얘기하던 건 이게 아니잖아.',
      chinese: {
        hanzi: ['哪儿跟哪儿啊', '我们', '讨论', '的', '不', '是', '这', '个'],
        pinyin: [
          'nǎr gēn nǎr a',
          'wǒmen',
          'tǎolùn',
          'de',
          'bú',
          'shì',
          'zhè',
          'ge',
        ],
      },
    },
    {
      id: 'sentence23',
      level: 5,
      isFinal: true,
      korean: '이게 무슨 소리야, 우리가 얘기하던 건 이게 아니잖아.',
      chinese: {
        hanzi: [
          '这',
          '是',
          '哪儿跟',
          '哪儿啊',
          '我们',
          '讨论',
          '的',
          '不',
          '是',
          '这',
          '个',
        ],
        pinyin: [
          'zhè',
          'shì',
          'nǎr gēn',
          'nǎr a',
          'wǒmen',
          'tǎolùn',
          'de',
          'bú',
          'shì',
          'zhè',
          'ge',
        ],
      },
    },
    //14번
    {
      id: 'sentence24',
      level: 1,
      isFinal: false,
      korean: '이게 뭐라고.',
      chinese: {
        hanzi: ['这', '算', '什么'],
        pinyin: ['zhè', 'suàn', 'shénme'],
      },
    },
    {
      id: 'sentence24',
      level: 2,
      isFinal: false,
      korean: '이 정도 돈이 뭐라고.',
      chinese: {
        hanzi: ['这', '点', '钱', '算', '什么'],
        pinyin: ['zhè', 'diǎn', 'qián', 'suàn', 'shénme'],
      },
    },
    {
      id: 'sentence24',
      level: 3,
      isFinal: true,
      korean: '이 정도 돈이 뭐라고, 내가 쏠게.',
      chinese: {
        hanzi: ['这', '点', '钱', '算', '什么', '我', '请', '客'],
        pinyin: ['zhè', 'diǎn', 'qián', 'suàn', 'shénme', 'wǒ', 'qǐng', 'kè'],
      },
    },
    //25번
    {
      id: 'sentence25',
      level: 1,
      isFinal: false,
      korean: '예술을 하다.',
      chinese: {
        hanzi: ['搞', '艺术'],
        pinyin: ['gǎo', 'yìshù'],
      },
    },
    {
      id: 'sentence25',
      level: 2,
      isFinal: false,
      korean: '예술을 할 재목',
      chinese: {
        hanzi: ['搞', '艺术', '的料'],
        pinyin: ['gǎo', 'yìshù', 'de liào'],
      },
    },
    {
      id: 'sentence25',
      level: 3,
      isFinal: false,
      korean: '예술 쪽에 어울리는 사람이 아니다.',
      chinese: {
        hanzi: ['不是', '搞', '艺术', '的', '料'],
        pinyin: ['bú shì', 'gǎo', 'yìshù', 'de', 'liào'],
      },
    },
    {
      id: 'sentence25',
      level: 4,
      isFinal: true,
      korean: '그는 예술 쪽에 어울리는 사람이 아니다.',
      chinese: {
        hanzi: ['他', '不', '是', '搞', '艺术', '的', '料'],
        pinyin: ['tā', 'bú', 'shì', 'gǎo', 'yìshù', 'de', 'liào'],
      },
    },

    {
      id: 'sentence26',
      level: 1,
      isFinal: false,
      korean: '계속 미루다.',
      chinese: {
        hanzi: ['拖', '下去'],
        pinyin: ['tuō', 'xiàqù'],
      },
    },
    {
      id: 'sentence26',
      level: 2,
      isFinal: false,
      korean: '계속 미루는 건 방법이 아니야.',
      chinese: {
        hanzi: ['拖下去', '不', '是', '办法'],
        pinyin: ['tuō xiàqù', 'bú', 'shì', 'bànfǎ'],
      },
    },
    {
      id: 'sentence26',
      level: 3,
      isFinal: false,
      korean: '이렇게 (계속) 미루는 건 방법이 아니야.',
      chinese: {
        hanzi: ['这样', '拖', '下去', '不', '是', '办法'],
        pinyin: ['zhèyàng', 'tuō', 'xiàqù', 'bú', 'shì', 'bànfǎ'],
      },
    },
    {
      id: 'sentence26',
      level: 4,
      isFinal: true,
      korean: '내 말은, 이렇게 (계속) 미루는 건 방법이 아니야.',
      chinese: {
        hanzi: ['我', '说', '这样', '拖', '下去', '不', '是', '办法'],
        pinyin: ['wǒ', 'shuō', 'zhèyàng', 'tuō', 'xiàqù', 'bú', 'shì', 'bànfǎ'],
      },
    },
    //27번
    {
      id: 'sentence27',
      level: 1,
      isFinal: false,
      korean: '나는 알고 있어.',
      chinese: {
        hanzi: ['我', '知道'],
        pinyin: ['wǒ', 'zhīdao'],
      },
    },
    {
      id: 'sentence27',
      level: 2,
      isFinal: false,
      korean: '나는 그럴 줄 알았어.',
      chinese: {
        hanzi: ['我', '就知道'],
        pinyin: ['wǒ', 'jiù zhīdao'],
      },
    },
    {
      id: 'sentence27',
      level: 3,
      isFinal: false,
      korean: '나는 성공할 줄 알았어. (= 나는 성공할 거라 예상했어)',
      chinese: {
        hanzi: ['我', '就', '知道', '会', '成功'],
        pinyin: ['wǒ', 'jiù', 'zhīdao', 'huì', 'chénggōng'],
      },
    },
    {
      id: 'sentence27',
      level: 4,
      isFinal: false,
      korean: '나는 분명 성공할 줄 알았어.',
      chinese: {
        hanzi: ['我', '就', '知道', '一定会', '成功'],
        pinyin: ['wǒ', 'jiù', 'zhīdao', 'yídìng huì', 'chénggōng'],
      },
    },
    {
      id: 'sentence27',
      level: 5,
      isFinal: true,
      korean: '나는 네가 분명 성공할 줄 알았어.',
      chinese: {
        hanzi: ['我', '就', '知道', '你', '一定', '会', '成功'],
        pinyin: ['wǒ', 'jiù', 'zhīdao', 'nǐ', 'yídìng', 'huì', 'chénggōng'],
      },
    },

    {
      id: 'sentence28',
      level: 1,
      isFinal: false,
      korean: '준비해야 한다.',
      chinese: {
        hanzi: ['该', '准备'],
        pinyin: ['gāi', 'zhǔnbèi'],
      },
    },
    {
      id: 'sentence28',
      level: 2,
      isFinal: false,
      korean: '준비해야 할 것.',
      chinese: {
        hanzi: ['该', '准备', '的'],
        pinyin: ['gāi', 'zhǔnbèi', 'de'],
      },
    },
    {
      id: 'sentence28',
      level: 3,
      isFinal: false,
      korean: '준비했다.',
      chinese: {
        hanzi: ['准备', '了'],
        pinyin: ['zhǔnbèi', 'le'],
      },
    },
    {
      id: 'sentence28',
      level: 4,
      isFinal: false,
      korean: '다 준비했다.',
      chinese: {
        hanzi: ['都', '准备', '了'],
        pinyin: ['dōu', 'zhǔnbèi', 'le'],
      },
    },
    {
      id: 'sentence28',
      level: 5,
      isFinal: true,
      korean: '준비해야 할 건 다 준비했다.',
      chinese: {
        hanzi: ['该', '准备', '的', '都', '准备', '了'],
        pinyin: ['gāi', 'zhǔnbèi', 'de', 'dōu', 'zhǔnbèi', 'le'],
      },
    },

    // 4번
    {
      id: 'sentence29',
      level: 1,
      isFinal: false,
      korean: '오해구나',
      chinese: {
        hanzi: ['是', '误会'],
        pinyin: ['shì', 'wùhuì'],
      },
    },
    {
      id: 'sentence29',
      level: 2,
      isFinal: false,
      korean: '알고 보니 오해였구나.',
      chinese: {
        hanzi: ['原来', '是', '误会'],
        pinyin: ['yuánlái', 'shì', 'wùhuì'],
      },
    },
    {
      id: 'sentence29',
      level: 3,
      isFinal: true,
      korean: '(알고 보니) 오해였구나, 내가 그럴 줄 알았어.',
      chinese: {
        hanzi: ['原来', '是', '误会', '我', '说', '呢'],
        pinyin: ['yuánlái', 'shì', 'wùhuì', 'wǒ', 'shuō', 'ne'],
      },
    },

    // 5번

    {
      id: 'sentence30',
      level: 1,
      isFinal: false,
      korean: '방법을 바꾸다.',
      chinese: {
        hanzi: ['换', '个', '办法'],
        pinyin: ['huàn', 'ge', 'bànfǎ'],
      },
    },
    {
      id: 'sentence30',
      level: 2,
      isFinal: false,
      korean: '방법을 바꿔서 한번 해보다.',
      chinese: {
        hanzi: ['换', '个', '办法', '试试'],
        pinyin: ['huàn', 'ge', 'bànfǎ', 'shìshi'],
      },
    },
    {
      id: 'sentence30',
      level: 3,
      isFinal: false,
      korean: '우리 방법을 바꿔서 한번 해보자.',
      chinese: {
        hanzi: ['我们', '换', '个', '办法', '试试'],
        pinyin: ['wǒmen', 'huàn', 'ge', 'bànfǎ', 'shìshi'],
      },
    },

    {
      id: 'sentence30',
      level: 4,
      isFinal: false,
      korean: '아니면 우리 방법을 바꿔서 한번 해볼까?',
      chinese: {
        hanzi: ['要不', '我们', '换', '个', '办法', '试试'],
        pinyin: ['yàobù', 'wǒmen', 'huàn', 'ge', 'bànfǎ', 'shìshi'],
      },
    },
    {
      id: 'sentence30',
      level: 5,
      isFinal: true,
      korean: '내 생각엔, 아니면 우리 방법을 바꿔서 한번 해볼까?',
      chinese: {
        hanzi: ['我', '说', '呀', '要不', '我们', '换', '个', '办法', '试试'],
        pinyin: [
          'wǒ',
          'shuō',
          'ya',
          'yàobù',
          'wǒmen',
          'huàn',
          'ge',
          'bànfǎ',
          'shìshi',
        ],
      },
    },
  ],
  week4: [
    // 1번
    {
      id: 'sentence31',
      level: 1,
      isFinal: false,
      korean: '생각하지 마',
      chinese: {
        hanzi: ['别', '想'],
        pinyin: ['bié', 'xiǎng'],
      },
    },
    {
      id: 'sentence31',
      level: 2,
      isFinal: false,
      korean: '너무 많이 생각하지 마.',
      chinese: {
        hanzi: ['别', '想', '太多'],
        pinyin: ['bié', 'xiǎng', 'tài duō'],
      },
    },
    {
      id: 'sentence31',
      level: 3,
      isFinal: false,
      korean: '너무 많이 생각하지 말고 한번 해봐.',
      chinese: {
        hanzi: ['别', '想', '太', '多', '试试'],
        pinyin: ['bié', 'xiǎng', 'tài', 'duō', 'shìshi'],
      },
    },
    {
      id: 'sentence31',
      level: 4,
      isFinal: true,
      korean: '너무 많이 생각하지 말고 한번 해보면 돼.',
      chinese: {
        hanzi: ['别', '想', '太', '多', '试试', '就', '是', '了'],
        pinyin: ['bié', 'xiǎng', 'tài', 'duō', 'shìshi', 'jiù', 'shì', 'le'],
      },
    },

    // 2번
    {
      id: 'sentence32',
      level: 1,
      isFinal: false,
      korean: '마음대로(그냥) 한번 말하다.',
      chinese: {
        hanzi: ['随便', '说说'],
        pinyin: ['suíbiàn', 'shuō shuo'],
      },
    },
    {
      id: 'sentence32',
      level: 2,
      isFinal: false,
      korean: '걔가 마음대로(그냥) 한번 말한 거야.',
      chinese: {
        hanzi: ['他', '随便', '说说'],
        pinyin: ['tā', 'suíbiàn', 'shuō shuo'],
      },
    },
    {
      id: 'sentence32',
      level: 3,
      isFinal: false,
      korean: '……, 걔가 마음대로(그냥) 한번 말했을 뿐이야.',
      chinese: {
        hanzi: ['他', '随便', '说说', '就', '是', '了'],
        pinyin: ['tā', 'suíbiàn', 'shuō shuo', 'jiù', 'shì', 'le'],
      },
    },
    {
      id: 'sentence32',
      level: 4,
      isFinal: false,
      korean: '마음에 담다.',
      chinese: {
        hanzi: ['往心里', '去'],
        pinyin: ['wǎng xīnli', 'qù'],
      },
    },
    {
      id: 'sentence32',
      level: 5,
      isFinal: false,
      korean: '마음에 담아두지 마.',
      chinese: {
        hanzi: ['别', '往', '心里', '去'],
        pinyin: ['bié', 'wǎng', 'xīnli', 'qù'],
      },
    },
    {
      id: 'sentence32',
      level: 6,
      isFinal: false,
      korean: '너는 마음에 담아두지 마.',
      chinese: {
        hanzi: ['你', '别', '往', '心里', '去'],
        pinyin: ['nǐ', 'bié', 'wǎng', 'xīnli', 'qù'],
      },
    },

    {
      id: 'sentence32',
      level: 7,
      isFinal: true,
      korean:
        '너는 마음에 담아두지 마, 걔가 마음대로(그냥) 한번 말했을 뿐이야.',
      chinese: {
        hanzi: [
          '你',
          '别',
          '往',
          '心里',
          '去',
          '他',
          '随便',
          '说说',
          '就',
          '是',
          '了',
        ],
        pinyin: [
          'nǐ',
          'bié',
          'wǎng',
          'xīnli',
          'qù',
          'tā',
          'suíbiàn',
          'shuō shuo',
          'jiù',
          'shì',
          'le',
        ],
      },
    },

    // 3번
    {
      id: 'sentence33',
      level: 1,
      isFinal: false,
      korean: '야근 해야 한다고?',
      chinese: {
        hanzi: ['要', '加班'],
        pinyin: ['yào', 'jiā bān'],
      },
    },
    {
      id: 'sentence33',
      level: 2,
      isFinal: false,
      korean: '또 야근 해야 한다고?',
      chinese: {
        hanzi: ['还', '要', '加', '班'],
        pinyin: ['hái', 'yào', 'jiā', 'bān'],
      },
    },
    {
      id: 'sentence33',
      level: 3,
      isFinal: false,
      korean: '주말에 또 야근 해야 한다고?',
      chinese: {
        hanzi: ['周末', '还', '要', '加', '班'],
        pinyin: ['zhōumò', 'hái', 'yào', 'jiā', 'bān'],
      },
    },
    {
      id: 'sentence33',
      level: 4,
      isFinal: true,
      korean: '주말에 또 야근 해야 한다고? 농담하지 마.',
      chinese: {
        hanzi: ['周末', '还', '要', '加', '班', '开', '什么', '玩笑'],
        pinyin: [
          'zhōumò',
          'hái',
          'yào',
          'jiā',
          'bān',
          'kāi',
          'shénme',
          'wánxiào',
        ],
      },
    },
    //14번
    {
      id: 'sentence34',
      level: 1,
      isFinal: false,
      korean: '잊었어?',
      chinese: {
        hanzi: ['忘', '了'],
        pinyin: ['wàng', 'le'],
      },
    },
    {
      id: 'sentence34',
      level: 2,
      isFinal: false,
      korean: '너 잊었어?',
      chinese: {
        hanzi: ['你', '忘', '了'],
        pinyin: ['nǐ', 'wàng', 'le'],
      },
    },
    {
      id: 'sentence34',
      level: 3,
      isFinal: false,
      korean: '이렇게 중요한 일을 너 잊었어?',
      chinese: {
        hanzi: ['这么', '重要', '的', '事', '你', '忘', '了'],
        pinyin: ['zhème', 'zhòngyào', 'de', 'shì', 'nǐ', 'wàng', 'le'],
      },
    },
    {
      id: 'sentence34',
      level: 4,
      isFinal: true,
      korean: '이렇게 중요한 일을 너 잊었어? 제정신이야?',
      chinese: {
        hanzi: [
          '这么',
          '重要',
          '的',
          '事',
          '你',
          '忘',
          '了',
          '开',
          '什么',
          '玩笑',
        ],
        pinyin: [
          'zhème',
          'zhòngyào',
          'de',
          'shì',
          'nǐ',
          'wàng',
          'le',
          'kāi',
          'shénme',
          'wánxiào',
        ],
      },
    },
    //25번
    {
      id: 'sentence35',
      level: 1,
      isFinal: false,
      korean: '몰라보겠다, 몰랐다',
      chinese: {
        hanzi: ['看', '不', '出来'],
        pinyin: ['kàn', 'bu', 'chūlái'],
      },
    },
    {
      id: 'sentence35',
      level: 2,
      isFinal: false,
      korean: '진짜 몰라보겠다(몰랐다)',
      chinese: {
        hanzi: ['真', '看', '不', '出来'],
        pinyin: ['zhēn', 'kàn', 'bu', 'chūlái'],
      },
    },
    {
      id: 'sentence35',
      level: 3,
      isFinal: false,
      korean: '이렇게 대단한 줄은 진짜 몰랐어.',
      chinese: {
        hanzi: ['真', '看', '不', '出来', '这么', '厉害'],
        pinyin: ['zhēn', 'kàn', 'bu', 'chūlái', 'zhème', 'lìhai'],
      },
    },
    {
      id: 'sentence35',
      level: 4,
      isFinal: true,
      korean: '네가 이렇게 대단할 줄은 진짜 몰랐어.',
      chinese: {
        hanzi: ['真', '看', '不', '出来', '你', '这么', '厉害'],
        pinyin: ['zhēn', 'kàn', 'bu', 'chūlái', 'nǐ', 'zhème', 'lìhai'],
      },
    },
    // 36번
    {
      id: 'sentence36',
      level: 1,
      isFinal: false,
      korean: '그건 그렇긴 하네, ……',
      chinese: {
        hanzi: ['那', '倒', '也是'],
        pinyin: ['nà', 'dào', 'yě shì'],
      },
    },
    {
      id: 'sentence36',
      level: 2,
      isFinal: false,
      korean: '그건 그렇긴 하네, 걔는 노력해.',
      chinese: {
        hanzi: ['那', '倒', '也', '是', '他', '很', '努力'],
        pinyin: ['nà', 'dào', 'yě', 'shì', 'tā', 'hěn', 'nǔlì'],
      },
    },
    {
      id: 'sentence36',
      level: 3,
      isFinal: false,
      korean: '그건 그렇긴 하네, 걔는 확실히 정말 노력해.',
      chinese: {
        hanzi: ['那', '倒', '也', '是', '他', '确实', '很', '努力'],
        pinyin: ['nà', 'dào', 'yě', 'shì', 'tā', 'quèshí', 'hěn', 'nǔlì'],
      },
    },
    {
      id: 'sentence36',
      level: 4,
      isFinal: true,
      korean: '그건 그렇긴 하네, 걔는 평소에 (확실히) 정말 노력하지.',
      chinese: {
        hanzi: ['那', '倒', '也', '是', '他', '平时', '确实', '很', '努力'],
        pinyin: [
          'nà',
          'dào',
          'yě',
          'shì',
          'tā',
          'píngshí',
          'quèshí',
          'hěn',
          'nǔlì',
        ],
      },
    },
    //37번
    {
      id: 'sentence37',
      level: 1,
      isFinal: false,
      korean: '벌써 2년이나 됐어.',
      chinese: {
        hanzi: ['都', '两', '年', '了'],
        pinyin: ['dōu', 'liǎng', 'nián', 'le'],
      },
    },
    {
      id: 'sentence37',
      level: 2,
      isFinal: false,
      korean: '벌써 2년이나 됐는데 계속 잊지 못했어.',
      chinese: {
        hanzi: ['都', '两', '年', '了', '一直', '没', '忘'],
        pinyin: ['dōu', 'liǎng', 'nián', 'le', 'yìzhí', 'méi', 'wàng'],
      },
    },
    {
      id: 'sentence37',
      level: 3,
      isFinal: false,
      korean: '벌써 2년이나 됐는데 나는 계속 잊지 못했어.',
      chinese: {
        hanzi: ['都', '两', '年', '了', '我', '一直', '没', '忘'],
        pinyin: ['dōu', 'liǎng', 'nián', 'le', 'wǒ', 'yìzhí', 'méi', 'wàng'],
      },
    },
    {
      id: 'sentence37',
      level: 4,
      isFinal: true,
      korean: '벌써 2년이나 됐는데 이 일을 나는 계속 잊지 못했어.',
      chinese: {
        hanzi: ['都', '两', '年', '了', '我', '一直', '没', '忘'],
        pinyin: [
          'dōu',
          'liǎng',
          'nián',
          'le',
          'zhè',
          'jiàn',
          'shì',
          'wǒ',
          'yìzhí',
          'méi',
          'wàng',
        ],
      },
    },
    // 38번
    {
      id: 'sentence38',
      level: 1,
      isFinal: false,
      korean: '벌써 사흘이나 됐어.',
      chinese: {
        hanzi: ['都', '三', '天', '了'],
        pinyin: ['dōu', 'sān', 'tiān', 'le'],
      },
    },
    {
      id: 'sentence38',
      level: 2,
      isFinal: false,
      korean: '벌써 사흘이나 됐는데 답장이 없어.',
      chinese: {
        hanzi: ['都', '三天', '了', '没', '回', '消息'],
        pinyin: ['dōu', 'sān tiān', 'le', 'méi', 'huí', 'xiāoxi'],
      },
    },
    {
      id: 'sentence38',
      level: 3,
      isFinal: false,
      korean: '벌써 사흘이나 됐는데 아직도 답장이 없어.',
      chinese: {
        hanzi: ['都', '三', '天', '了', '还', '没', '回', '消息'],
        pinyin: ['dōu', 'sān', 'tiān', 'le', 'hái', 'méi', 'huí', 'xiāoxi'],
      },
    },
    {
      id: 'sentence38',
      level: 4,
      isFinal: true,
      korean: '벌써 사흘이나 됐는데 걔는 아직도 답장이 없어.',
      chinese: {
        hanzi: ['都', '三', '天', '了', '他', '还', '没', '回', '消息'],
        pinyin: [
          'dōu',
          'sān',
          'tiān',
          'le',
          'tā',
          'hái',
          'méi',
          'huí',
          'xiāoxi',
        ],
      },
    },
    // 39번
    {
      id: 'sentence39',
      level: 1,
      isFinal: false,
      korean: '해결할 수 있어.',
      chinese: {
        hanzi: ['能', '解决'],
        pinyin: ['néng', 'jiějué'],
      },
    },
    {
      id: 'sentence39',
      level: 2,
      isFinal: false,
      korean: '일은 해결할 수 있어.',
      chinese: {
        hanzi: ['事情', '能', '解决'],
        pinyin: ['shìqing', 'néng', 'jiějué'],
      },
    },
    {
      id: 'sentence39',
      level: 3,
      isFinal: true,
      korean: '일은 아무튼 해결되겠지.',
      chinese: {
        hanzi: ['事情', '总', '能', '解决', '吧'],
        pinyin: ['shìqing', 'zǒng', 'néng', 'jiějué', 'ba'],
      },
    },

    // 5번

    {
      id: 'sentence40',
      level: 1,
      isFinal: false,
      korean: '이 일은 쉽지 않아.',
      chinese: {
        hanzi: ['这', '件', '事', '不', '容易'],
        pinyin: ['zhè', 'jiàn', 'shì', 'bù', 'róngyì'],
      },
    },
    {
      id: 'sentence40',
      level: 2,
      isFinal: false,
      korean: '이 일은 확실히 쉽지 않아.',
      chinese: {
        hanzi: ['这', '件', '事', '确实', '不', '容易'],
        pinyin: ['zhè', 'jiàn', 'shì', 'quèshí', 'bù', 'róngyì'],
      },
    },
    {
      id: 'sentence40',
      level: 3,
      isFinal: false,
      korean: '이 일은 확실히 쉽지 않지만, 한 걸음 물러서서 말하면 ……',
      chinese: {
        hanzi: [
          '这',
          '件',
          '事',
          '确实',
          '不',
          '容易',
          '但',
          '退',
          '一步',
          '说',
        ],
        pinyin: [
          'zhè',
          'jiàn',
          'shì',
          'quèshí',
          'bù',
          'róngyì',
          'dàn',
          'tuì',
          'yí bù',
          'shuō',
        ],
      },
    },

    {
      id: 'sentence40',
      level: 4,
      isFinal: false,
      korean:
        '이 일은 확실히 쉽지 않지만, 한 걸음 물러서서 말하면 설령 실패하더라도 ……',
      chinese: {
        hanzi: [
          '这',
          '件',
          '事',
          '确实',
          '不',
          '容易',
          '但',
          '退',
          '一步',
          '说',
          '就算',
          '失败',
          '了',
        ],
        pinyin: [
          'zhè',
          'jiàn',
          'shì',
          'quèshí',
          'bù',
          'róngyì',
          'dàn',
          'tuì',
          'yí bù',
          'shuō',
          'jiùsuàn',
          'shībài',
          'le',
        ],
      },
    },
    {
      id: 'sentence40',
      level: 5,
      isFinal: true,
      korean:
        '이 일은 확실히 쉽지 않지만, 한 걸음 물러서서 말하면 설령 실패하더라도 한 번의 경험인 셈이야.',
      chinese: {
        hanzi: [
          '这件事',
          '确实',
          '不',
          '容易',
          '但',
          '退一步',
          '说',
          '就算',
          '失败了',
          '也算',
          '一次',
          '经验',
        ],
        pinyin: [
          'zhè jiàn shì',
          'quèshí',
          'bù',
          'róngyì',
          'dàn',
          'tuì yí bù',
          'shuō',
          'jiùsuàn',
          'shībài le',
          'yě suàn',
          'yí cì',
          'jīngyàn',
        ],
      },
    },
  ],
};

// 전역 변수로 내보내기
window.sentenceData = sentenceData;